# Generated by Django 5.1.3 on 2025-02-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('1zone', 'Zone 1'), ('2zone', 'Zone 2'), ('3zone', 'Zone 3')], max_length=10)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('name_farm', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.BooleanField(default=False)),
                ('timer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='smartfarm.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='token_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='smartfarm.user'),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='smartfarm.device')),
            ],
        ),
    ]
