# Generated by Django 5.1.3 on 2025-02-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0003_user_email_user_phonenumber_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
    ]
